# Numpy
https://doorbw.tistory.com/171
* C언어로 구현된 파이썬 라이브러리
* 수치계산을 위한 라이브러리
* 벡터 및 행렬 연산을 위한 편리한 기능 제공
* 표로 데이터를 분석하는 pandas와 그림을 그리는 matplotlib도 있음

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

## array 생성 : np.array

In [6]:
ysArray = [1,2,3,4,5,6,7] #파이썬 리스트. 무조건 쉼표 있어야 함. 매트랩처럼 띄어쓰기로는 안됨.
print("ysArray:\n{}".format(ysArray))
ysArray

ysArray:
[1, 2, 3, 4, 5, 6, 7]


[1, 2, 3, 4, 5, 6, 7]

In [7]:
arr1 = np.array(ysArray) #위의 리스트와 numpy를 이용하여 array 정의
print(arr1)

[1 2 3 4 5 6 7]


#### shape, dtype

In [8]:
arr1.shape #열과 행 출력

(7,)

In [11]:
arr2 = np.array([1,2,3,4])
arr2

array([1, 2, 3, 4])

In [12]:
arr2.shape

(4,)

In [13]:
arr2.dtype #data type

dtype('int32')

In [14]:
data2 = [1,2,3.14,4] #파이썬 리스트
data2

[1, 2, 3.14, 4]

In [15]:
arr3 = np.array(data2)
arr3

array([1.  , 2.  , 3.14, 4.  ])

In [16]:
arr3.dtype

dtype('float64')

### 2차원 배열 생성 : zeros, ones

In [17]:
np.zeros(4) #0을 채운 array

array([0., 0., 0., 0.])

In [18]:
np.zeros((2,3)) #2x3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### arange : 1씩 증가하는 배열 생성

In [21]:
np.arange(3)

array([0, 1, 2])

In [22]:
np.arange(4,9)

array([4, 5, 6, 7, 8])

-----------------------


## array간의 연산
### 기본 연산

In [34]:
arr1 = np.array([[9,8,7],[6,5,4]])
arr2 = np.array([[10,20,30],[40,50,60]])
print(arr1,'\n')
print(arr2,'\n')

print('덧셈\n\n',arr1+arr2,'\n')
print('뺄셈\n\n',arr1-arr2,'\n')
print('곱셈\n\n',arr1*arr2,'\n')
print('나눗셈\n\n',arr1/arr2,'\n')

[[9 8 7]
 [6 5 4]] 

[[10 20 30]
 [40 50 60]] 

덧셈

 [[19 28 37]
 [46 55 64]] 

뺄셈

 [[ -1 -12 -23]
 [-34 -45 -56]] 

곱셈

 [[ 90 160 210]
 [240 250 240]] 

나눗셈

 [[0.9        0.4        0.23333333]
 [0.15       0.1        0.06666667]] 



### 스칼라 곱, 제곱

In [37]:
arr1 * 10

array([[90, 80, 70],
       [60, 50, 40]])

In [38]:
arr1**2

array([[81, 64, 49],
       [36, 25, 16]], dtype=int32)

### 크기가 다른 array간의 연산도 지원 _ broadcasted

In [35]:
arr3 = np.array([17,17,17])
arr2+arr3

array([[27, 37, 47],
       [57, 67, 77]])

--------------------------
## Indexing

In [41]:
arr4 = np.arange(10)
print(arr4)
arr4[0]

[0 1 2 3 4 5 6 7 8 9]


0

In [40]:
arr4[4]

4

In [43]:
arr4[1:9] #1~8

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
arr4[:] #all

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
print(arr2)
arr2[1,:] #1행 전체 출력

[[10 20 30]
 [40 50 60]]


array([40, 50, 60])

In [48]:
arr2[1,2] #1행 2열의 요소 꺼내기

60

----------------------------------
## randn

In [53]:
rarr = np.random.randn(3,2)
rarr

array([[ 1.06441161, -0.83441234],
       [ 0.42086565, -0.11812778],
       [ 1.23632799, -1.77227936]])

In [55]:
rarr[rarr[:,0]<0,:]  # 0번째 열의 값이 0보다 작은 모든 값

array([], shape=(0, 2), dtype=float64)

In [56]:
rarr[rarr[:,1]<0,:] # 1번째 열의 값이 0보다 작은 모든 값
# 반복 실행을 위해 Ctrl + Enter 로 반복 테스트 해보세요

array([[ 1.06441161, -0.83441234],
       [ 0.42086565, -0.11812778],
       [ 1.23632799, -1.77227936]])

In [60]:
np.abs(rarr) # 각 성분의 절대값

array([[1.06441161, 0.83441234],
       [0.42086565, 0.11812778],
       [1.23632799, 1.77227936]])

In [62]:
np.sqrt(rarr) # 각 성분의 제곱근
np.square(rarr) #각 성분의 제곱
np.exp(rarr) #지수
np.log(rarr) #로그
np.log2(rarr)
#제곱근 계산이 불가능한 경우의 nan때문에 워닝이 뜸

C:\Users\zmffh\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[1.03170326,        nan],
       [0.64874159,        nan],
       [1.11190287,        nan]])

array([[1.13297208, 0.69624395],
       [0.17712789, 0.01395417],
       [1.5285069 , 3.14097414]])

array([[2.89913266, 0.43412953],
       [1.52327961, 0.88858251],
       [3.44294768, 0.16994518]])

C:\Users\zmffh\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in log
  after removing the cwd from sys.path.


array([[ 0.06242217,         nan],
       [-0.86544163,         nan],
       [ 0.21214569,         nan]])

C:\Users\zmffh\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log2
  """


array([[ 0.09005615,         nan],
       [-1.24856834,         nan],
       [ 0.30606153,         nan]])

In [63]:
rarr
np.sum(rarr,axis=0) #각 열에 대한 합
np.sum(rarr,axis=1) #행

array([[ 1.06441161, -0.83441234],
       [ 0.42086565, -0.11812778],
       [ 1.23632799, -1.77227936]])

array([ 2.72160525, -2.72481947])

array([ 0.22999928,  0.30273787, -0.53595137])

In [64]:
np.std(rarr) #표준편차
np.var(rarr) #분산
np.min(rarr)
np.max(rarr)

1.0559180366623042

1.114962900148775

-1.772279362642699

1.2363279896142951

In [66]:
rarr
np.sort(rarr,axis=0) #각각의 열에 대해 정렬 (전체 아님. 각각의 열에 대해서만!)
np.sort(rarr,axis=1) #행

array([[ 1.06441161, -0.83441234],
       [ 0.42086565, -0.11812778],
       [ 1.23632799, -1.77227936]])

array([[ 0.42086565, -1.77227936],
       [ 1.06441161, -0.83441234],
       [ 1.23632799, -0.11812778]])

array([[-0.83441234,  1.06441161],
       [-0.11812778,  0.42086565],
       [-1.77227936,  1.23632799]])